;;; this file is automatically generated, do not edit
#||
Copyright (c) 2015-2016 The Khronos Group Inc.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and/or associated documentation files (the
"Materials"), to deal in the Materials without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Materials, and to
permit persons to whom the Materials are furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Materials.

THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.

------------------------------------------------------------------------
||#

(defpackage #:cl-vulkan-bindings
  (:use #:cl #:cffi)
  (:nicknames #:%vk)
  (:export
    #:pfn-allocation-function ;; :func
    #:pfn-debug-report-callback-ext ;; :func
    #:pfn-free-function ;; :func
    #:pfn-internal-allocation-notification ;; :func
    #:pfn-internal-free-notification ;; :func
    #:pfn-reallocation-function ;; :func
    #:pfn-void-function ;; :func
    #:access-flag-bits ;; :enum
    #:access-flags ;; :bitmask
    #:allocation-callbacks ;; :struct
    #:android-surface-create-flags-khr ;; :bitmask
    #:android-surface-create-info-khr ;; :struct
    #:application-info ;; :struct
    #:attachment-description ;; :struct
    #:attachment-description-flag-bits ;; :enum
    #:attachment-description-flags ;; :bitmask
    #:attachment-load-op ;; :enum
    #:attachment-reference ;; :struct
    #:attachment-store-op ;; :enum
    #:bind-sparse-info ;; :struct
    #:blend-factor ;; :enum
    #:blend-op ;; :enum
    #:bool32 ;; :alias
    #:border-color ;; :enum
    #:buffer ;; :non-dispatch-handle
    #:buffer-copy ;; :struct
    #:buffer-create-flag-bits ;; :enum
    #:buffer-create-flags ;; :bitmask
    #:buffer-create-info ;; :struct
    #:buffer-image-copy ;; :struct
    #:buffer-memory-barrier ;; :struct
    #:buffer-usage-flag-bits ;; :enum
    #:buffer-usage-flags ;; :bitmask
    #:buffer-view ;; :non-dispatch-handle
    #:buffer-view-create-flag-bits ;; :enum
    #:buffer-view-create-flags ;; :bitmask
    #:buffer-view-create-info ;; :struct
    #:clear-attachment ;; :struct
    #:clear-color-value ;; :union
    #:clear-depth-stencil-value ;; :struct
    #:clear-rect ;; :struct
    #:clear-value ;; :union
    #:color-component-flag-bits ;; :enum
    #:color-component-flags ;; :bitmask
    #:color-space-khr ;; :enum
    #:command-buffer ;; :handle
    #:command-buffer-allocate-info ;; :struct
    #:command-buffer-begin-info ;; :struct
    #:command-buffer-inheritance-info ;; :struct
    #:command-buffer-level ;; :enum
    #:command-buffer-reset-flag-bits ;; :enum
    #:command-buffer-reset-flags ;; :bitmask
    #:command-buffer-usage-flag-bits ;; :enum
    #:command-buffer-usage-flags ;; :bitmask
    #:command-pool ;; :non-dispatch-handle
    #:command-pool-create-flag-bits ;; :enum
    #:command-pool-create-flags ;; :bitmask
    #:command-pool-create-info ;; :struct
    #:command-pool-reset-flag-bits ;; :enum
    #:command-pool-reset-flags ;; :bitmask
    #:compare-op ;; :enum
    #:component-mapping ;; :struct
    #:component-swizzle ;; :enum
    #:composite-alpha-flag-bits-khr ;; :enum
    #:composite-alpha-flags-khr ;; :bitmask
    #:compute-pipeline-create-info ;; :struct
    #:copy-descriptor-set ;; :struct
    #:cull-mode-flag-bits ;; :enum
    #:cull-mode-flags ;; :bitmask
    #:debug-report-callback-create-info-ext ;; :struct
    #:debug-report-callback-ext ;; :non-dispatch-handle
    #:debug-report-error-ext ;; :enum
    #:debug-report-flag-bits-ext ;; :enum
    #:debug-report-flags-ext ;; :bitmask
    #:debug-report-object-type-ext ;; :enum
    #:dependency-flag-bits ;; :enum
    #:dependency-flags ;; :bitmask
    #:descriptor-buffer-info ;; :struct
    #:descriptor-image-info ;; :struct
    #:descriptor-pool ;; :non-dispatch-handle
    #:descriptor-pool-create-flag-bits ;; :enum
    #:descriptor-pool-create-flags ;; :bitmask
    #:descriptor-pool-create-info ;; :struct
    #:descriptor-pool-reset-flags ;; :bitmask
    #:descriptor-pool-size ;; :struct
    #:descriptor-set ;; :non-dispatch-handle
    #:descriptor-set-allocate-info ;; :struct
    #:descriptor-set-layout ;; :non-dispatch-handle
    #:descriptor-set-layout-binding ;; :struct
    #:descriptor-set-layout-create-flag-bits ;; :enum
    #:descriptor-set-layout-create-flags ;; :bitmask
    #:descriptor-set-layout-create-info ;; :struct
    #:descriptor-type ;; :enum
    #:device ;; :handle
    #:device-create-flag-bits ;; :enum
    #:device-create-flags ;; :bitmask
    #:device-create-info ;; :struct
    #:device-memory ;; :non-dispatch-handle
    #:device-queue-create-flag-bits ;; :enum
    #:device-queue-create-flags ;; :bitmask
    #:device-queue-create-info ;; :struct
    #:device-size ;; :alias
    #:dispatch-indirect-command ;; :struct
    #:display-khr ;; :non-dispatch-handle
    #:display-mode-create-flags-khr ;; :bitmask
    #:display-mode-create-info-khr ;; :struct
    #:display-mode-khr ;; :non-dispatch-handle
    #:display-mode-parameters-khr ;; :struct
    #:display-mode-properties-khr ;; :struct
    #:display-plane-alpha-flag-bits-khr ;; :enum
    #:display-plane-alpha-flags-khr ;; :bitmask
    #:display-plane-capabilities-khr ;; :struct
    #:display-plane-properties-khr ;; :struct
    #:display-present-info-khr ;; :struct
    #:display-properties-khr ;; :struct
    #:display-surface-create-flags-khr ;; :bitmask
    #:display-surface-create-info-khr ;; :struct
    #:draw-indexed-indirect-command ;; :struct
    #:draw-indirect-command ;; :struct
    #:dynamic-state ;; :enum
    #:event ;; :non-dispatch-handle
    #:event-create-flags ;; :bitmask
    #:event-create-info ;; :struct
    #:extension-properties ;; :struct
    #:extent-2d ;; :struct
    #:extent-3d ;; :struct
    #:fence ;; :non-dispatch-handle
    #:fence-create-flag-bits ;; :enum
    #:fence-create-flags ;; :bitmask
    #:fence-create-info ;; :struct
    #:filter ;; :enum
    #:flags ;; :alias
    #:format ;; :enum
    #:format-feature-flag-bits ;; :enum
    #:format-feature-flags ;; :bitmask
    #:format-properties ;; :struct
    #:framebuffer ;; :non-dispatch-handle
    #:framebuffer-create-flag-bits ;; :enum
    #:framebuffer-create-flags ;; :bitmask
    #:framebuffer-create-info ;; :struct
    #:front-face ;; :enum
    #:graphics-pipeline-create-info ;; :struct
    #:image ;; :non-dispatch-handle
    #:image-aspect-flag-bits ;; :enum
    #:image-aspect-flags ;; :bitmask
    #:image-blit ;; :struct
    #:image-copy ;; :struct
    #:image-create-flag-bits ;; :enum
    #:image-create-flags ;; :bitmask
    #:image-create-info ;; :struct
    #:image-format-properties ;; :struct
    #:image-layout ;; :enum
    #:image-memory-barrier ;; :struct
    #:image-resolve ;; :struct
    #:image-subresource ;; :struct
    #:image-subresource-layers ;; :struct
    #:image-subresource-range ;; :struct
    #:image-tiling ;; :enum
    #:image-type ;; :enum
    #:image-usage-flag-bits ;; :enum
    #:image-usage-flags ;; :bitmask
    #:image-view ;; :non-dispatch-handle
    #:image-view-create-flags ;; :bitmask
    #:image-view-create-info ;; :struct
    #:image-view-type ;; :enum
    #:index-type ;; :enum
    #:instance ;; :handle
    #:instance-create-flag-bits ;; :enum
    #:instance-create-flags ;; :bitmask
    #:instance-create-info ;; :struct
    #:internal-allocation-type ;; :enum
    #:layer-properties ;; :struct
    #:logic-op ;; :enum
    #:mapped-memory-range ;; :struct
    #:memory-allocate-info ;; :struct
    #:memory-barrier ;; :struct
    #:memory-heap ;; :struct
    #:memory-heap-flag-bits ;; :enum
    #:memory-heap-flags ;; :bitmask
    #:memory-map-flags ;; :bitmask
    #:memory-property-flag-bits ;; :enum
    #:memory-property-flags ;; :bitmask
    #:memory-requirements ;; :struct
    #:memory-type ;; :struct
    #:mir-surface-create-flags-khr ;; :bitmask
    #:mir-surface-create-info-khr ;; :struct
    #:offset-2d ;; :struct
    #:offset-3d ;; :struct
    #:physical-device ;; :handle
    #:physical-device-features ;; :struct
    #:physical-device-limits ;; :struct
    #:physical-device-memory-properties ;; :struct
    #:physical-device-properties ;; :struct
    #:physical-device-sparse-properties ;; :struct
    #:physical-device-type ;; :enum
    #:pipeline ;; :non-dispatch-handle
    #:pipeline-bind-point ;; :enum
    #:pipeline-cache ;; :non-dispatch-handle
    #:pipeline-cache-create-flag-bits ;; :enum
    #:pipeline-cache-create-flags ;; :bitmask
    #:pipeline-cache-create-info ;; :struct
    #:pipeline-cache-header-version ;; :enum
    #:pipeline-color-blend-attachment-state ;; :struct
    #:pipeline-color-blend-state-create-flag-bits ;; :enum
    #:pipeline-color-blend-state-create-flags ;; :bitmask
    #:pipeline-color-blend-state-create-info ;; :struct
    #:pipeline-create-flag-bits ;; :enum
    #:pipeline-create-flags ;; :bitmask
    #:pipeline-depth-stencil-state-create-flag-bits ;; :enum
    #:pipeline-depth-stencil-state-create-flags ;; :bitmask
    #:pipeline-depth-stencil-state-create-info ;; :struct
    #:pipeline-dynamic-state-create-flag-bits ;; :enum
    #:pipeline-dynamic-state-create-flags ;; :bitmask
    #:pipeline-dynamic-state-create-info ;; :struct
    #:pipeline-input-assembly-state-create-flag-bits ;; :enum
    #:pipeline-input-assembly-state-create-flags ;; :bitmask
    #:pipeline-input-assembly-state-create-info ;; :struct
    #:pipeline-layout ;; :non-dispatch-handle
    #:pipeline-layout-create-flag-bits ;; :enum
    #:pipeline-layout-create-flags ;; :bitmask
    #:pipeline-layout-create-info ;; :struct
    #:pipeline-multisample-state-create-flag-bits ;; :enum
    #:pipeline-multisample-state-create-flags ;; :bitmask
    #:pipeline-multisample-state-create-info ;; :struct
    #:pipeline-rasterization-state-create-flag-bits ;; :enum
    #:pipeline-rasterization-state-create-flags ;; :bitmask
    #:pipeline-rasterization-state-create-info ;; :struct
    #:pipeline-shader-stage-create-flag-bits ;; :enum
    #:pipeline-shader-stage-create-flags ;; :bitmask
    #:pipeline-shader-stage-create-info ;; :struct
    #:pipeline-stage-flag-bits ;; :enum
    #:pipeline-stage-flags ;; :bitmask
    #:pipeline-tessellation-state-create-flag-bits ;; :enum
    #:pipeline-tessellation-state-create-flags ;; :bitmask
    #:pipeline-tessellation-state-create-info ;; :struct
    #:pipeline-vertex-input-state-create-flag-bits ;; :enum
    #:pipeline-vertex-input-state-create-flags ;; :bitmask
    #:pipeline-vertex-input-state-create-info ;; :struct
    #:pipeline-viewport-state-create-flag-bits ;; :enum
    #:pipeline-viewport-state-create-flags ;; :bitmask
    #:pipeline-viewport-state-create-info ;; :struct
    #:polygon-mode ;; :enum
    #:present-info-khr ;; :struct
    #:present-mode-khr ;; :enum
    #:primitive-topology ;; :enum
    #:push-constant-range ;; :struct
    #:query-control-flag-bits ;; :enum
    #:query-control-flags ;; :bitmask
    #:query-pipeline-statistic-flag-bits ;; :enum
    #:query-pipeline-statistic-flags ;; :bitmask
    #:query-pool ;; :non-dispatch-handle
    #:query-pool-create-flag-bits ;; :enum
    #:query-pool-create-flags ;; :bitmask
    #:query-pool-create-info ;; :struct
    #:query-result-flag-bits ;; :enum
    #:query-result-flags ;; :bitmask
    #:query-type ;; :enum
    #:queue ;; :handle
    #:queue-family-properties ;; :struct
    #:queue-flag-bits ;; :enum
    #:queue-flags ;; :bitmask
    #:rect-2d ;; :struct
    #:rect-3d ;; :struct
    #:render-pass ;; :non-dispatch-handle
    #:render-pass-begin-info ;; :struct
    #:render-pass-create-flag-bits ;; :enum
    #:render-pass-create-flags ;; :bitmask
    #:render-pass-create-info ;; :struct
    #:result ;; :enum
    #:sample-count-flag-bits ;; :enum
    #:sample-count-flags ;; :bitmask
    #:sample-mask ;; :alias
    #:sampler ;; :non-dispatch-handle
    #:sampler-address-mode ;; :enum
    #:sampler-create-flag-bits ;; :enum
    #:sampler-create-flags ;; :bitmask
    #:sampler-create-info ;; :struct
    #:sampler-mipmap-mode ;; :enum
    #:semaphore ;; :non-dispatch-handle
    #:semaphore-create-flags ;; :bitmask
    #:semaphore-create-info ;; :struct
    #:shader-module ;; :non-dispatch-handle
    #:shader-module-create-flags ;; :bitmask
    #:shader-module-create-info ;; :struct
    #:shader-stage-flag-bits ;; :enum
    #:shader-stage-flags ;; :bitmask
    #:sharing-mode ;; :enum
    #:sparse-buffer-memory-bind-info ;; :struct
    #:sparse-image-format-flag-bits ;; :enum
    #:sparse-image-format-flags ;; :bitmask
    #:sparse-image-format-properties ;; :struct
    #:sparse-image-memory-bind ;; :struct
    #:sparse-image-memory-bind-info ;; :struct
    #:sparse-image-memory-requirements ;; :struct
    #:sparse-image-opaque-memory-bind-info ;; :struct
    #:sparse-memory-bind ;; :struct
    #:sparse-memory-bind-flag-bits ;; :enum
    #:sparse-memory-bind-flags ;; :bitmask
    #:specialization-info ;; :struct
    #:specialization-map-entry ;; :struct
    #:stencil-face-flag-bits ;; :enum
    #:stencil-face-flags ;; :bitmask
    #:stencil-op ;; :enum
    #:stencil-op-state ;; :struct
    #:structure-type ;; :enum
    #:submit-info ;; :struct
    #:subpass-contents ;; :enum
    #:subpass-dependency ;; :struct
    #:subpass-description ;; :struct
    #:subpass-description-flags ;; :bitmask
    #:subresource-layout ;; :struct
    #:surface-capabilities-khr ;; :struct
    #:surface-format-khr ;; :struct
    #:surface-khr ;; :non-dispatch-handle
    #:surface-transform-flag-bits-khr ;; :enum
    #:surface-transform-flags-khr ;; :bitmask
    #:swapchain-create-flags-khr ;; :bitmask
    #:swapchain-create-info-khr ;; :struct
    #:swapchain-khr ;; :non-dispatch-handle
    #:system-allocation-scope ;; :enum
    #:vertex-input-attribute-description ;; :struct
    #:vertex-input-binding-description ;; :struct
    #:vertex-input-rate ;; :enum
    #:viewport ;; :struct
    #:wayland-surface-create-flags-khr ;; :bitmask
    #:wayland-surface-create-info-khr ;; :struct
    #:win32-surface-create-flags-khr ;; :bitmask
    #:win32-surface-create-info-khr ;; :struct
    #:write-descriptor-set ;; :struct
    #:xcb-surface-create-flags-khr ;; :bitmask
    #:xcb-surface-create-info-khr ;; :struct
    #:xlib-surface-create-flags-khr ;; :bitmask
    #:xlib-surface-create-info-khr ;; :struct

    #:acquire-next-image-khr
    #:allocate-command-buffers
    #:allocate-descriptor-sets
    #:allocate-memory
    #:begin-command-buffer
    #:bind-buffer-memory
    #:bind-image-memory
    #:cmd-begin-query
    #:cmd-begin-render-pass
    #:cmd-bind-descriptor-sets
    #:cmd-bind-index-buffer
    #:cmd-bind-pipeline
    #:cmd-bind-vertex-buffers
    #:cmd-blit-image
    #:cmd-clear-attachments
    #:cmd-clear-color-image
    #:cmd-clear-depth-stencil-image
    #:cmd-copy-buffer
    #:cmd-copy-buffer-to-image
    #:cmd-copy-image
    #:cmd-copy-image-to-buffer
    #:cmd-copy-query-pool-results
    #:cmd-dispatch
    #:cmd-dispatch-indirect
    #:cmd-draw
    #:cmd-draw-indexed
    #:cmd-draw-indexed-indirect
    #:cmd-draw-indirect
    #:cmd-end-query
    #:cmd-end-render-pass
    #:cmd-execute-commands
    #:cmd-fill-buffer
    #:cmd-next-subpass
    #:cmd-pipeline-barrier
    #:cmd-push-constants
    #:cmd-reset-event
    #:cmd-reset-query-pool
    #:cmd-resolve-image
    #:cmd-set-blend-constants
    #:cmd-set-depth-bias
    #:cmd-set-depth-bounds
    #:cmd-set-event
    #:cmd-set-line-width
    #:cmd-set-scissor
    #:cmd-set-stencil-compare-mask
    #:cmd-set-stencil-reference
    #:cmd-set-stencil-write-mask
    #:cmd-set-viewport
    #:cmd-update-buffer
    #:cmd-wait-events
    #:cmd-write-timestamp
    #:create-android-surface-khr
    #:create-buffer
    #:create-buffer-view
    #:create-command-pool
    #:create-compute-pipelines
    #:create-debug-report-callback-ext
    #:create-descriptor-pool
    #:create-descriptor-set-layout
    #:create-device
    #:create-display-mode-khr
    #:create-display-plane-surface-khr
    #:create-event
    #:create-fence
    #:create-framebuffer
    #:create-graphics-pipelines
    #:create-image
    #:create-image-view
    #:create-instance
    #:create-mir-surface-khr
    #:create-pipeline-cache
    #:create-pipeline-layout
    #:create-query-pool
    #:create-render-pass
    #:create-sampler
    #:create-semaphore
    #:create-shader-module
    #:create-shared-swapchains-khr
    #:create-swapchain-khr
    #:create-wayland-surface-khr
    #:create-win32-surface-khr
    #:create-xcb-surface-khr
    #:create-xlib-surface-khr
    #:debug-report-message-ext
    #:destroy-buffer
    #:destroy-buffer-view
    #:destroy-command-pool
    #:destroy-debug-report-callback-ext
    #:destroy-descriptor-pool
    #:destroy-descriptor-set-layout
    #:destroy-device
    #:destroy-event
    #:destroy-fence
    #:destroy-framebuffer
    #:destroy-image
    #:destroy-image-view
    #:destroy-instance
    #:destroy-pipeline
    #:destroy-pipeline-cache
    #:destroy-pipeline-layout
    #:destroy-query-pool
    #:destroy-render-pass
    #:destroy-sampler
    #:destroy-semaphore
    #:destroy-shader-module
    #:destroy-surface-khr
    #:destroy-swapchain-khr
    #:device-wait-idle
    #:end-command-buffer
    #:enumerate-device-extension-properties
    #:enumerate-device-layer-properties
    #:enumerate-instance-extension-properties
    #:enumerate-instance-layer-properties
    #:enumerate-physical-devices
    #:flush-mapped-memory-ranges
    #:free-command-buffers
    #:free-descriptor-sets
    #:free-memory
    #:get-buffer-memory-requirements
    #:get-device-memory-commitment
    #:get-device-proc-addr
    #:get-device-queue
    #:get-display-mode-properties-khr
    #:get-display-plane-capabilities-khr
    #:get-display-plane-supported-displays-khr
    #:get-event-status
    #:get-fence-status
    #:get-image-memory-requirements
    #:get-image-sparse-memory-requirements
    #:get-image-subresource-layout
    #:get-instance-proc-addr
    #:get-physical-device-display-plane-properties-khr
    #:get-physical-device-display-properties-khr
    #:get-physical-device-features
    #:get-physical-device-format-properties
    #:get-physical-device-image-format-properties
    #:get-physical-device-memory-properties
    #:get-physical-device-mir-presentation-support-khr
    #:get-physical-device-properties
    #:get-physical-device-queue-family-properties
    #:get-physical-device-sparse-image-format-properties
    #:get-physical-device-surface-capabilities-khr
    #:get-physical-device-surface-formats-khr
    #:get-physical-device-surface-present-modes-khr
    #:get-physical-device-surface-support-khr
    #:get-physical-device-wayland-presentation-support-khr
    #:get-physical-device-win32-presentation-support-khr
    #:get-physical-device-xcb-presentation-support-khr
    #:get-physical-device-xlib-presentation-support-khr
    #:get-pipeline-cache-data
    #:get-query-pool-results
    #:get-render-area-granularity
    #:get-swapchain-images-khr
    #:invalidate-mapped-memory-ranges
    #:map-memory
    #:merge-pipeline-caches
    #:queue-bind-sparse
    #:queue-present-khr
    #:queue-submit
    #:queue-wait-idle
    #:reset-command-buffer
    #:reset-command-pool
    #:reset-descriptor-pool
    #:reset-event
    #:reset-fences
    #:set-event
    #:unmap-memory
    #:update-descriptor-sets
    #:wait-for-fences
))
