;;; this file is automatically generated, do not edit
#||
Copyright (c) 2015-2017 The Khronos Group Inc.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and/or associated documentation files (the
"Materials"), to deal in the Materials without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Materials, and to
permit persons to whom the Materials are furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Materials.

THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.

------------------------------------------------------------------------
||#

(in-package #:cl-vulkan-bindings)

(defvkextfun ("vkAcquireNextImage2KHX" acquire-next-image-2-khx) checked-result
  (device device)
  (p-acquire-info (:pointer (:struct acquire-next-image-info-khx)))
  (p-image-index (:pointer :uint32)))

(defvkextfun ("vkAcquireNextImageKHR" acquire-next-image-khr) checked-result
  (device device)
  (swapchain swapchain-khr) ;; :EXTERNSYNC "true"
  (timeout :uint64)
  (semaphore semaphore) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (fence fence) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-image-index (:pointer :uint32)))

(defvkextfun ("vkAcquireXlibDisplayEXT" acquire-xlib-display-ext) checked-result
  (physical-device physical-device)
  (dpy (:pointer display))
  (display display-khr))

(defvkfun ("vkAllocateCommandBuffers" allocate-command-buffers) checked-result
  (device device)
  (p-allocate-info (:pointer (:struct command-buffer-allocate-info))) ;; :EXTERNSYNC "pAllocateInfo::commandPool"
  (p-command-buffers (:pointer command-buffer)) ;; :LEN "pAllocateInfo::commandBufferCount"
)

(defvkfun ("vkAllocateDescriptorSets" allocate-descriptor-sets) checked-result
  (device device)
  (p-allocate-info (:pointer (:struct descriptor-set-allocate-info))) ;; :EXTERNSYNC "pAllocateInfo::descriptorPool"
  (p-descriptor-sets (:pointer descriptor-set)) ;; :LEN "pAllocateInfo::descriptorSetCount"
)

(defvkfun ("vkAllocateMemory" allocate-memory) checked-result
  (device device)
  (p-allocate-info (:pointer (:struct memory-allocate-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-memory (:pointer device-memory)))

(defvkfun ("vkBeginCommandBuffer" begin-command-buffer) checked-result
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (p-begin-info (:pointer (:struct command-buffer-begin-info))))

(defvkfun ("vkBindBufferMemory" bind-buffer-memory) checked-result
  (device device)
  (buffer buffer) ;; :EXTERNSYNC "true"
  (memory device-memory)
  (memory-offset device-size))

(defvkextfun ("vkBindBufferMemory2KHX" bind-buffer-memory-2-khx) checked-result
  (device device)
  (bind-info-count :uint32)
  (p-bind-infos (:pointer (:struct bind-buffer-memory-info-khx))) ;; :LEN "bindInfoCount"
)

(defvkfun ("vkBindImageMemory" bind-image-memory) checked-result
  (device device)
  (image image) ;; :EXTERNSYNC "true"
  (memory device-memory)
  (memory-offset device-size))

(defvkextfun ("vkBindImageMemory2KHX" bind-image-memory-2-khx) checked-result
  (device device)
  (bind-info-count :uint32)
  (p-bind-infos (:pointer (:struct bind-image-memory-info-khx))) ;; :LEN "bindInfoCount"
)

(defvkfun ("vkCmdBeginQuery" cmd-begin-query) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (query-pool query-pool)
  (query :uint32)
  (flags query-control-flags) ;; :OPTIONAL "true"
)

(defvkfun ("vkCmdBeginRenderPass" cmd-begin-render-pass) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (p-render-pass-begin (:pointer (:struct render-pass-begin-info)))
  (contents subpass-contents))

(defvkfun ("vkCmdBindDescriptorSets" cmd-bind-descriptor-sets) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (pipeline-bind-point pipeline-bind-point)
  (layout pipeline-layout)
  (first-set :uint32)
  (descriptor-set-count :uint32)
  (p-descriptor-sets (:pointer descriptor-set)) ;; :LEN "descriptorSetCount"
  (dynamic-offset-count :uint32) ;; :OPTIONAL "true"
  (p-dynamic-offsets (:pointer :uint32)) ;; :LEN "dynamicOffsetCount"
)

(defvkfun ("vkCmdBindIndexBuffer" cmd-bind-index-buffer) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (buffer buffer)
  (offset device-size)
  (index-type index-type))

(defvkfun ("vkCmdBindPipeline" cmd-bind-pipeline) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (pipeline-bind-point pipeline-bind-point)
  (pipeline pipeline))

(defvkfun ("vkCmdBindVertexBuffers" cmd-bind-vertex-buffers) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (first-binding :uint32)
  (binding-count :uint32)
  (p-buffers (:pointer buffer)) ;; :LEN "bindingCount"
  (p-offsets (:pointer device-size)) ;; :LEN "bindingCount"
)

(defvkfun ("vkCmdBlitImage" cmd-blit-image) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (src-image image)
  (src-image-layout image-layout)
  (dst-image image)
  (dst-image-layout image-layout)
  (region-count :uint32)
  (p-regions (:pointer (:struct image-blit))) ;; :LEN "regionCount"
  (filter filter))

(defvkfun ("vkCmdClearAttachments" cmd-clear-attachments) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (attachment-count :uint32)
  (p-attachments (:pointer (:struct clear-attachment))) ;; :LEN "attachmentCount"
  (rect-count :uint32)
  (p-rects (:pointer (:struct clear-rect))) ;; :LEN "rectCount"
)

(defvkfun ("vkCmdClearColorImage" cmd-clear-color-image) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (image image)
  (image-layout image-layout)
  (p-color (:pointer (:union clear-color-value)))
  (range-count :uint32)
  (p-ranges (:pointer (:struct image-subresource-range))) ;; :LEN "rangeCount"
)

(defvkfun ("vkCmdClearDepthStencilImage" cmd-clear-depth-stencil-image) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (image image)
  (image-layout image-layout)
  (p-depth-stencil (:pointer (:struct clear-depth-stencil-value)))
  (range-count :uint32)
  (p-ranges (:pointer (:struct image-subresource-range))) ;; :LEN "rangeCount"
)

(defvkfun ("vkCmdCopyBuffer" cmd-copy-buffer) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (src-buffer buffer)
  (dst-buffer buffer)
  (region-count :uint32)
  (p-regions (:pointer (:struct buffer-copy))) ;; :LEN "regionCount"
)

(defvkfun ("vkCmdCopyBufferToImage" cmd-copy-buffer-to-image) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (src-buffer buffer)
  (dst-image image)
  (dst-image-layout image-layout)
  (region-count :uint32)
  (p-regions (:pointer (:struct buffer-image-copy))) ;; :LEN "regionCount"
)

(defvkfun ("vkCmdCopyImage" cmd-copy-image) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (src-image image)
  (src-image-layout image-layout)
  (dst-image image)
  (dst-image-layout image-layout)
  (region-count :uint32)
  (p-regions (:pointer (:struct image-copy))) ;; :LEN "regionCount"
)

(defvkfun ("vkCmdCopyImageToBuffer" cmd-copy-image-to-buffer) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (src-image image)
  (src-image-layout image-layout)
  (dst-buffer buffer)
  (region-count :uint32)
  (p-regions (:pointer (:struct buffer-image-copy))) ;; :LEN "regionCount"
)

(defvkfun ("vkCmdCopyQueryPoolResults" cmd-copy-query-pool-results) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (query-pool query-pool)
  (first-query :uint32)
  (query-count :uint32)
  (dst-buffer buffer)
  (dst-offset device-size)
  (stride device-size)
  (flags query-result-flags) ;; :OPTIONAL "true"
)

(defvkextfun ("vkCmdDebugMarkerBeginEXT" cmd-debug-marker-begin-ext) :void
  (command-buffer command-buffer)
  (p-marker-info (:pointer (:struct debug-marker-marker-info-ext))))

(defvkextfun ("vkCmdDebugMarkerEndEXT" cmd-debug-marker-end-ext) :void
  (command-buffer command-buffer))

(defvkextfun ("vkCmdDebugMarkerInsertEXT" cmd-debug-marker-insert-ext) :void
  (command-buffer command-buffer)
  (p-marker-info (:pointer (:struct debug-marker-marker-info-ext))))

(defvkfun ("vkCmdDispatch" cmd-dispatch) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (group-count-x :uint32)
  (group-count-y :uint32)
  (group-count-z :uint32))

(defvkextfun ("vkCmdDispatchBaseKHX" cmd-dispatch-base-khx) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (base-group-x :uint32)
  (base-group-y :uint32)
  (base-group-z :uint32)
  (group-count-x :uint32)
  (group-count-y :uint32)
  (group-count-z :uint32))

(defvkfun ("vkCmdDispatchIndirect" cmd-dispatch-indirect) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (buffer buffer)
  (offset device-size))

(defvkfun ("vkCmdDraw" cmd-draw) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (vertex-count :uint32)
  (instance-count :uint32)
  (first-vertex :uint32)
  (first-instance :uint32))

(defvkfun ("vkCmdDrawIndexed" cmd-draw-indexed) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (index-count :uint32)
  (instance-count :uint32)
  (first-index :uint32)
  (vertex-offset :int32)
  (first-instance :uint32))

(defvkfun ("vkCmdDrawIndexedIndirect" cmd-draw-indexed-indirect) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (buffer buffer)
  (offset device-size)
  (draw-count :uint32)
  (stride :uint32))

(defvkextfun ("vkCmdDrawIndexedIndirectCountAMD" cmd-draw-indexed-indirect-count-amd) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (buffer buffer)
  (offset device-size)
  (count-buffer buffer)
  (count-buffer-offset device-size)
  (max-draw-count :uint32)
  (stride :uint32))

(defvkfun ("vkCmdDrawIndirect" cmd-draw-indirect) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (buffer buffer)
  (offset device-size)
  (draw-count :uint32)
  (stride :uint32))

(defvkextfun ("vkCmdDrawIndirectCountAMD" cmd-draw-indirect-count-amd) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (buffer buffer)
  (offset device-size)
  (count-buffer buffer)
  (count-buffer-offset device-size)
  (max-draw-count :uint32)
  (stride :uint32))

(defvkfun ("vkCmdEndQuery" cmd-end-query) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (query-pool query-pool)
  (query :uint32))

(defvkfun ("vkCmdEndRenderPass" cmd-end-render-pass) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
)

(defvkfun ("vkCmdExecuteCommands" cmd-execute-commands) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (command-buffer-count :uint32)
  (p-command-buffers (:pointer command-buffer)) ;; :LEN "commandBufferCount"
)

(defvkfun ("vkCmdFillBuffer" cmd-fill-buffer) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (dst-buffer buffer)
  (dst-offset device-size)
  (size device-size)
  (data :uint32))

(defvkfun ("vkCmdNextSubpass" cmd-next-subpass) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (contents subpass-contents))

(defvkfun ("vkCmdPipelineBarrier" cmd-pipeline-barrier) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (src-stage-mask pipeline-stage-flags)
  (dst-stage-mask pipeline-stage-flags)
  (dependency-flags dependency-flags) ;; :OPTIONAL "true"
  (memory-barrier-count :uint32) ;; :OPTIONAL "true"
  (p-memory-barriers (:pointer (:struct memory-barrier))) ;; :LEN "memoryBarrierCount"
  (buffer-memory-barrier-count :uint32) ;; :OPTIONAL "true"
  (p-buffer-memory-barriers (:pointer (:struct buffer-memory-barrier))) ;; :LEN "bufferMemoryBarrierCount"
  (image-memory-barrier-count :uint32) ;; :OPTIONAL "true"
  (p-image-memory-barriers (:pointer (:struct image-memory-barrier))) ;; :LEN "imageMemoryBarrierCount"
)

(defvkextfun ("vkCmdProcessCommandsNVX" cmd-process-commands-nvx) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (p-process-commands-info (:pointer (:struct cmd-process-commands-info-nvx))))

(defvkfun ("vkCmdPushConstants" cmd-push-constants) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (layout pipeline-layout)
  (stage-flags shader-stage-flags)
  (offset :uint32)
  (size :uint32)
  (p-values (:pointer :void)) ;; :LEN "size"
)

(defvkextfun ("vkCmdPushDescriptorSetKHR" cmd-push-descriptor-set-khr) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (pipeline-bind-point pipeline-bind-point)
  (layout pipeline-layout)
  (set :uint32)
  (descriptor-write-count :uint32)
  (p-descriptor-writes (:pointer (:struct write-descriptor-set))) ;; :LEN "descriptorWriteCount"
)

(defvkextfun ("vkCmdPushDescriptorSetWithTemplateKHR" cmd-push-descriptor-set-with-template-khr) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (descriptor-update-template descriptor-update-template-khr)
  (layout pipeline-layout)
  (set :uint32)
  (p-data (:pointer :void)))

(defvkextfun ("vkCmdReserveSpaceForCommandsNVX" cmd-reserve-space-for-commands-nvx) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (p-reserve-space-info (:pointer (:struct cmd-reserve-space-for-commands-info-nvx))))

(defvkfun ("vkCmdResetEvent" cmd-reset-event) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (event event)
  (stage-mask pipeline-stage-flags))

(defvkfun ("vkCmdResetQueryPool" cmd-reset-query-pool) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (query-pool query-pool)
  (first-query :uint32)
  (query-count :uint32))

(defvkfun ("vkCmdResolveImage" cmd-resolve-image) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (src-image image)
  (src-image-layout image-layout)
  (dst-image image)
  (dst-image-layout image-layout)
  (region-count :uint32)
  (p-regions (:pointer (:struct image-resolve))) ;; :LEN "regionCount"
)

(defvkfun ("vkCmdSetBlendConstants" cmd-set-blend-constants) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (blend-constants :float))

(defvkfun ("vkCmdSetDepthBias" cmd-set-depth-bias) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (depth-bias-constant-factor :float)
  (depth-bias-clamp :float)
  (depth-bias-slope-factor :float))

(defvkfun ("vkCmdSetDepthBounds" cmd-set-depth-bounds) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (min-depth-bounds :float)
  (max-depth-bounds :float))

(defvkextfun ("vkCmdSetDeviceMaskKHX" cmd-set-device-mask-khx) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (device-mask :uint32))

(defvkextfun ("vkCmdSetDiscardRectangleEXT" cmd-set-discard-rectangle-ext) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (first-discard-rectangle :uint32)
  (discard-rectangle-count :uint32)
  (p-discard-rectangles (:pointer (:struct rect-2d))) ;; :LEN "discardRectangleCount"
)

(defvkfun ("vkCmdSetEvent" cmd-set-event) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (event event)
  (stage-mask pipeline-stage-flags))

(defvkfun ("vkCmdSetLineWidth" cmd-set-line-width) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (line-width :float))

(defvkfun ("vkCmdSetScissor" cmd-set-scissor) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (first-scissor :uint32)
  (scissor-count :uint32)
  (p-scissors (:pointer (:struct rect-2d))) ;; :LEN "scissorCount"
)

(defvkfun ("vkCmdSetStencilCompareMask" cmd-set-stencil-compare-mask) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (face-mask stencil-face-flags)
  (compare-mask :uint32))

(defvkfun ("vkCmdSetStencilReference" cmd-set-stencil-reference) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (face-mask stencil-face-flags)
  (reference :uint32))

(defvkfun ("vkCmdSetStencilWriteMask" cmd-set-stencil-write-mask) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (face-mask stencil-face-flags)
  (write-mask :uint32))

(defvkfun ("vkCmdSetViewport" cmd-set-viewport) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (first-viewport :uint32)
  (viewport-count :uint32)
  (p-viewports (:pointer (:struct viewport))) ;; :LEN "viewportCount" :NOAUTOVALIDITY "true"
)

(defvkextfun ("vkCmdSetViewportWScalingNV" cmd-set-viewport-w-scaling-nv) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (first-viewport :uint32)
  (viewport-count :uint32)
  (p-viewport-w-scalings (:pointer (:struct viewport-w-scaling-nv))) ;; :LEN "viewportCount" :NOAUTOVALIDITY "true"
)

(defvkfun ("vkCmdUpdateBuffer" cmd-update-buffer) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (dst-buffer buffer)
  (dst-offset device-size)
  (data-size device-size)
  (p-data (:pointer :void)) ;; :LEN "dataSize"
)

(defvkfun ("vkCmdWaitEvents" cmd-wait-events) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (event-count :uint32)
  (p-events (:pointer event)) ;; :LEN "eventCount"
  (src-stage-mask pipeline-stage-flags)
  (dst-stage-mask pipeline-stage-flags)
  (memory-barrier-count :uint32) ;; :OPTIONAL "true"
  (p-memory-barriers (:pointer (:struct memory-barrier))) ;; :LEN "memoryBarrierCount"
  (buffer-memory-barrier-count :uint32) ;; :OPTIONAL "true"
  (p-buffer-memory-barriers (:pointer (:struct buffer-memory-barrier))) ;; :LEN "bufferMemoryBarrierCount"
  (image-memory-barrier-count :uint32) ;; :OPTIONAL "true"
  (p-image-memory-barriers (:pointer (:struct image-memory-barrier))) ;; :LEN "imageMemoryBarrierCount"
)

(defvkfun ("vkCmdWriteTimestamp" cmd-write-timestamp) :void
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (pipeline-stage pipeline-stage-flag-bits)
  (query-pool query-pool)
  (query :uint32))

(defvkextfun ("vkCreateAndroidSurfaceKHR" create-android-surface-khr) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct android-surface-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkfun ("vkCreateBuffer" create-buffer) checked-result
  (device device)
  (p-create-info (:pointer (:struct buffer-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-buffer (:pointer buffer)))

(defvkfun ("vkCreateBufferView" create-buffer-view) checked-result
  (device device)
  (p-create-info (:pointer (:struct buffer-view-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-view (:pointer buffer-view)))

(defvkfun ("vkCreateCommandPool" create-command-pool) checked-result
  (device device)
  (p-create-info (:pointer (:struct command-pool-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-command-pool (:pointer command-pool)))

(defvkfun ("vkCreateComputePipelines" create-compute-pipelines) checked-result
  (device device)
  (pipeline-cache pipeline-cache) ;; :OPTIONAL "true"
  (create-info-count :uint32)
  (p-create-infos (:pointer (:struct compute-pipeline-create-info))) ;; :LEN "createInfoCount"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-pipelines (:pointer pipeline)) ;; :LEN "createInfoCount"
)

(defvkextfun ("vkCreateDebugReportCallbackEXT" create-debug-report-callback-ext) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct debug-report-callback-create-info-ext)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-callback (:pointer debug-report-callback-ext)))

(defvkfun ("vkCreateDescriptorPool" create-descriptor-pool) checked-result
  (device device)
  (p-create-info (:pointer (:struct descriptor-pool-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-descriptor-pool (:pointer descriptor-pool)))

(defvkfun ("vkCreateDescriptorSetLayout" create-descriptor-set-layout) checked-result
  (device device)
  (p-create-info (:pointer (:struct descriptor-set-layout-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-set-layout (:pointer descriptor-set-layout)))

(defvkextfun ("vkCreateDescriptorUpdateTemplateKHR" create-descriptor-update-template-khr) checked-result
  (device device)
  (p-create-info (:pointer (:struct descriptor-update-template-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-descriptor-update-template (:pointer descriptor-update-template-khr)))

(defvkfun ("vkCreateDevice" create-device) checked-result
  (physical-device physical-device)
  (p-create-info (:pointer (:struct device-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-device (:pointer device)))

(defvkextfun ("vkCreateDisplayModeKHR" create-display-mode-khr) checked-result
  (physical-device physical-device)
  (display display-khr) ;; :EXTERNSYNC "true"
  (p-create-info (:pointer (:struct display-mode-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-mode (:pointer display-mode-khr)))

(defvkextfun ("vkCreateDisplayPlaneSurfaceKHR" create-display-plane-surface-khr) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct display-surface-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkfun ("vkCreateEvent" create-event) checked-result
  (device device)
  (p-create-info (:pointer (:struct event-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-event (:pointer event)))

(defvkfun ("vkCreateFence" create-fence) checked-result
  (device device)
  (p-create-info (:pointer (:struct fence-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-fence (:pointer fence)))

(defvkfun ("vkCreateFramebuffer" create-framebuffer) checked-result
  (device device)
  (p-create-info (:pointer (:struct framebuffer-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-framebuffer (:pointer framebuffer)))

(defvkfun ("vkCreateGraphicsPipelines" create-graphics-pipelines) checked-result
  (device device)
  (pipeline-cache pipeline-cache) ;; :OPTIONAL "true"
  (create-info-count :uint32)
  (p-create-infos (:pointer (:struct graphics-pipeline-create-info))) ;; :LEN "createInfoCount"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-pipelines (:pointer pipeline)) ;; :LEN "createInfoCount"
)

(defvkextfun ("vkCreateIOSSurfaceMVK" create-i-o-s-surface-mvk) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct i-o-s-surface-create-info-mvk)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkfun ("vkCreateImage" create-image) checked-result
  (device device)
  (p-create-info (:pointer (:struct image-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-image (:pointer image)))

(defvkfun ("vkCreateImageView" create-image-view) checked-result
  (device device)
  (p-create-info (:pointer (:struct image-view-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-view (:pointer image-view)))

(defvkextfun ("vkCreateIndirectCommandsLayoutNVX" create-indirect-commands-layout-nvx) checked-result
  (device device)
  (p-create-info (:pointer (:struct indirect-commands-layout-create-info-nvx)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-indirect-commands-layout (:pointer indirect-commands-layout-nvx)))

(defvkfun ("vkCreateInstance" create-instance) checked-result
  (p-create-info (:pointer (:struct instance-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-instance (:pointer instance)))

(defvkextfun ("vkCreateMacOSSurfaceMVK" create-mac-o-s-surface-mvk) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct mac-o-s-surface-create-info-mvk)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkextfun ("vkCreateMirSurfaceKHR" create-mir-surface-khr) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct mir-surface-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkextfun ("vkCreateObjectTableNVX" create-object-table-nvx) checked-result
  (device device)
  (p-create-info (:pointer (:struct object-table-create-info-nvx)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-object-table (:pointer object-table-nvx)))

(defvkfun ("vkCreatePipelineCache" create-pipeline-cache) checked-result
  (device device)
  (p-create-info (:pointer (:struct pipeline-cache-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-pipeline-cache (:pointer pipeline-cache)))

(defvkfun ("vkCreatePipelineLayout" create-pipeline-layout) checked-result
  (device device)
  (p-create-info (:pointer (:struct pipeline-layout-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-pipeline-layout (:pointer pipeline-layout)))

(defvkfun ("vkCreateQueryPool" create-query-pool) checked-result
  (device device)
  (p-create-info (:pointer (:struct query-pool-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-query-pool (:pointer query-pool)))

(defvkfun ("vkCreateRenderPass" create-render-pass) checked-result
  (device device)
  (p-create-info (:pointer (:struct render-pass-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-render-pass (:pointer render-pass)))

(defvkfun ("vkCreateSampler" create-sampler) checked-result
  (device device)
  (p-create-info (:pointer (:struct sampler-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-sampler (:pointer sampler)))

(defvkfun ("vkCreateSemaphore" create-semaphore) checked-result
  (device device)
  (p-create-info (:pointer (:struct semaphore-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-semaphore (:pointer semaphore)))

(defvkfun ("vkCreateShaderModule" create-shader-module) checked-result
  (device device)
  (p-create-info (:pointer (:struct shader-module-create-info)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-shader-module (:pointer shader-module)))

(defvkextfun ("vkCreateSharedSwapchainsKHR" create-shared-swapchains-khr) checked-result
  (device device)
  (swapchain-count :uint32)
  (p-create-infos (:pointer (:struct swapchain-create-info-khr))) ;; :LEN "swapchainCount" :EXTERNSYNC "pCreateInfos[].surface,pCreateInfos[].oldSwapchain"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-swapchains (:pointer swapchain-khr)) ;; :LEN "swapchainCount"
)

(defvkextfun ("vkCreateSwapchainKHR" create-swapchain-khr) checked-result
  (device device)
  (p-create-info (:pointer (:struct swapchain-create-info-khr))) ;; :EXTERNSYNC "pCreateInfo.surface,pCreateInfo.oldSwapchain"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-swapchain (:pointer swapchain-khr)))

(defvkextfun ("vkCreateViSurfaceNN" create-vi-surface-nn) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct vi-surface-create-info-nn)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkextfun ("vkCreateWaylandSurfaceKHR" create-wayland-surface-khr) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct wayland-surface-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkextfun ("vkCreateWin32SurfaceKHR" create-win32-surface-khr) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct win32-surface-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkextfun ("vkCreateXcbSurfaceKHR" create-xcb-surface-khr) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct xcb-surface-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkextfun ("vkCreateXlibSurfaceKHR" create-xlib-surface-khr) checked-result
  (instance instance)
  (p-create-info (:pointer (:struct xlib-surface-create-info-khr)))
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
  (p-surface (:pointer surface-khr)))

(defvkextfun ("vkDebugMarkerSetObjectNameEXT" debug-marker-set-object-name-ext) checked-result
  (device device)
  (p-name-info (:pointer (:struct debug-marker-object-name-info-ext))) ;; :EXTERNSYNC "pNameInfo.object"
)

(defvkextfun ("vkDebugMarkerSetObjectTagEXT" debug-marker-set-object-tag-ext) checked-result
  (device device)
  (p-tag-info (:pointer (:struct debug-marker-object-tag-info-ext))) ;; :EXTERNSYNC "pTagInfo.object"
)

(defvkextfun ("vkDebugReportMessageEXT" debug-report-message-ext) :void
  (instance instance)
  (flags debug-report-flags-ext)
  (object-type debug-report-object-type-ext)
  (object :uint64)
  (location size-t)
  (message-code :int32)
  (p-layer-prefix :string) ;; :LEN "null-terminated"
  (p-message :string) ;; :LEN "null-terminated"
)

(defvkfun ("vkDestroyBuffer" destroy-buffer) :void
  (device device)
  (buffer buffer) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyBufferView" destroy-buffer-view) :void
  (device device)
  (buffer-view buffer-view) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyCommandPool" destroy-command-pool) :void
  (device device)
  (command-pool command-pool) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkextfun ("vkDestroyDebugReportCallbackEXT" destroy-debug-report-callback-ext) :void
  (instance instance)
  (callback debug-report-callback-ext) ;; :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyDescriptorPool" destroy-descriptor-pool) :void
  (device device)
  (descriptor-pool descriptor-pool) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyDescriptorSetLayout" destroy-descriptor-set-layout) :void
  (device device)
  (descriptor-set-layout descriptor-set-layout) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkextfun ("vkDestroyDescriptorUpdateTemplateKHR" destroy-descriptor-update-template-khr) :void
  (device device)
  (descriptor-update-template descriptor-update-template-khr) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyDevice" destroy-device) :void
  (device device) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyEvent" destroy-event) :void
  (device device)
  (event event) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyFence" destroy-fence) :void
  (device device)
  (fence fence) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyFramebuffer" destroy-framebuffer) :void
  (device device)
  (framebuffer framebuffer) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyImage" destroy-image) :void
  (device device)
  (image image) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyImageView" destroy-image-view) :void
  (device device)
  (image-view image-view) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkextfun ("vkDestroyIndirectCommandsLayoutNVX" destroy-indirect-commands-layout-nvx) :void
  (device device)
  (indirect-commands-layout indirect-commands-layout-nvx)
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyInstance" destroy-instance) :void
  (instance instance) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkextfun ("vkDestroyObjectTableNVX" destroy-object-table-nvx) :void
  (device device)
  (object-table object-table-nvx) ;; :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyPipeline" destroy-pipeline) :void
  (device device)
  (pipeline pipeline) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyPipelineCache" destroy-pipeline-cache) :void
  (device device)
  (pipeline-cache pipeline-cache) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyPipelineLayout" destroy-pipeline-layout) :void
  (device device)
  (pipeline-layout pipeline-layout) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyQueryPool" destroy-query-pool) :void
  (device device)
  (query-pool query-pool) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyRenderPass" destroy-render-pass) :void
  (device device)
  (render-pass render-pass) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroySampler" destroy-sampler) :void
  (device device)
  (sampler sampler) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroySemaphore" destroy-semaphore) :void
  (device device)
  (semaphore semaphore) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDestroyShaderModule" destroy-shader-module) :void
  (device device)
  (shader-module shader-module) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkextfun ("vkDestroySurfaceKHR" destroy-surface-khr) :void
  (instance instance)
  (surface surface-khr) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkextfun ("vkDestroySwapchainKHR" destroy-swapchain-khr) :void
  (device device)
  (swapchain swapchain-khr) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkDeviceWaitIdle" device-wait-idle) checked-result
  (device device))

(defvkextfun ("vkDisplayPowerControlEXT" display-power-control-ext) checked-result
  (device device)
  (display display-khr)
  (p-display-power-info (:pointer (:struct display-power-info-ext))))

(defvkfun ("vkEndCommandBuffer" end-command-buffer) checked-result
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
)

(defvkfun ("vkEnumerateDeviceExtensionProperties" enumerate-device-extension-properties) checked-result
  (physical-device physical-device)
  (p-layer-name :string) ;; :OPTIONAL "true" :LEN "null-terminated"
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct extension-properties))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkfun ("vkEnumerateDeviceLayerProperties" enumerate-device-layer-properties) checked-result
  (physical-device physical-device)
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct layer-properties))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkfun ("vkEnumerateInstanceExtensionProperties" enumerate-instance-extension-properties) checked-result
  (p-layer-name :string) ;; :OPTIONAL "true" :LEN "null-terminated"
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct extension-properties))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkfun ("vkEnumerateInstanceLayerProperties" enumerate-instance-layer-properties) checked-result
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct layer-properties))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkextfun ("vkEnumeratePhysicalDeviceGroupsKHX" enumerate-physical-device-groups-khx) checked-result
  (instance instance)
  (p-physical-device-group-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-physical-device-group-properties (:pointer (:struct physical-device-group-properties-khx))) ;; :OPTIONAL "true" :LEN "pPhysicalDeviceGroupCount"
)

(defvkfun ("vkEnumeratePhysicalDevices" enumerate-physical-devices) checked-result
  (instance instance)
  (p-physical-device-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-physical-devices (:pointer physical-device)) ;; :OPTIONAL "true" :LEN "pPhysicalDeviceCount"
)

(defvkfun ("vkFlushMappedMemoryRanges" flush-mapped-memory-ranges) checked-result
  (device device)
  (memory-range-count :uint32)
  (p-memory-ranges (:pointer (:struct mapped-memory-range))) ;; :LEN "memoryRangeCount"
)

(defvkfun ("vkFreeCommandBuffers" free-command-buffers) :void
  (device device)
  (command-pool command-pool) ;; :EXTERNSYNC "true"
  (command-buffer-count :uint32)
  (p-command-buffers (:pointer command-buffer)) ;; :LEN "commandBufferCount" :NOAUTOVALIDITY "true" :EXTERNSYNC "true"
)

(defvkfun ("vkFreeDescriptorSets" free-descriptor-sets) checked-result
  (device device)
  (descriptor-pool descriptor-pool) ;; :EXTERNSYNC "true"
  (descriptor-set-count :uint32)
  (p-descriptor-sets (:pointer descriptor-set)) ;; :LEN "descriptorSetCount" :NOAUTOVALIDITY "true" :EXTERNSYNC "true"
)

(defvkfun ("vkFreeMemory" free-memory) :void
  (device device)
  (memory device-memory) ;; :OPTIONAL "true" :EXTERNSYNC "true"
  (p-allocator (:pointer (:struct allocation-callbacks))) ;; :OPTIONAL "true"
)

(defvkfun ("vkGetBufferMemoryRequirements" get-buffer-memory-requirements) :void
  (device device)
  (buffer buffer)
  (p-memory-requirements (:pointer (:struct memory-requirements))))

(defvkextfun ("vkGetDeviceGroupPeerMemoryFeaturesKHX" get-device-group-peer-memory-features-khx) :void
  (device device)
  (heap-index :uint32)
  (local-device-index :uint32)
  (remote-device-index :uint32)
  (p-peer-memory-features (:pointer peer-memory-feature-flags-khx)))

(defvkextfun ("vkGetDeviceGroupPresentCapabilitiesKHX" get-device-group-present-capabilities-khx) checked-result
  (device device)
  (p-device-group-present-capabilities (:pointer (:struct device-group-present-capabilities-khx))))

(defvkextfun ("vkGetDeviceGroupSurfacePresentModesKHX" get-device-group-surface-present-modes-khx) checked-result
  (device device)
  (surface surface-khr) ;; :EXTERNSYNC "true"
  (p-modes (:pointer device-group-present-mode-flags-khx)))

(defvkfun ("vkGetDeviceMemoryCommitment" get-device-memory-commitment) :void
  (device device)
  (memory device-memory)
  (p-committed-memory-in-bytes (:pointer device-size)))

(defvkfun ("vkGetDeviceProcAddr" get-device-proc-addr) pfn-void-function
  (device device)
  (p-name :string) ;; :LEN "null-terminated"
)

(defvkfun ("vkGetDeviceQueue" get-device-queue) :void
  (device device)
  (queue-family-index :uint32)
  (queue-index :uint32)
  (p-queue (:pointer queue)))

(defvkextfun ("vkGetDisplayModePropertiesKHR" get-display-mode-properties-khr) checked-result
  (physical-device physical-device)
  (display display-khr)
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct display-mode-properties-khr))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkextfun ("vkGetDisplayPlaneCapabilitiesKHR" get-display-plane-capabilities-khr) checked-result
  (physical-device physical-device)
  (mode display-mode-khr) ;; :EXTERNSYNC "true"
  (plane-index :uint32)
  (p-capabilities (:pointer (:struct display-plane-capabilities-khr))))

(defvkextfun ("vkGetDisplayPlaneSupportedDisplaysKHR" get-display-plane-supported-displays-khr) checked-result
  (physical-device physical-device)
  (plane-index :uint32)
  (p-display-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-displays (:pointer display-khr)) ;; :OPTIONAL "true" :LEN "pDisplayCount"
)

(defvkfun ("vkGetEventStatus" get-event-status) checked-result
  (device device)
  (event event))

(defvkfun ("vkGetFenceStatus" get-fence-status) checked-result
  (device device)
  (fence fence))

(defvkfun ("vkGetImageMemoryRequirements" get-image-memory-requirements) :void
  (device device)
  (image image)
  (p-memory-requirements (:pointer (:struct memory-requirements))))

(defvkfun ("vkGetImageSparseMemoryRequirements" get-image-sparse-memory-requirements) :void
  (device device)
  (image image)
  (p-sparse-memory-requirement-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-sparse-memory-requirements (:pointer (:struct sparse-image-memory-requirements))) ;; :OPTIONAL "true" :LEN "pSparseMemoryRequirementCount"
)

(defvkfun ("vkGetImageSubresourceLayout" get-image-subresource-layout) :void
  (device device)
  (image image)
  (p-subresource (:pointer (:struct image-subresource)))
  (p-layout (:pointer (:struct subresource-layout))))

(defvkfun ("vkGetInstanceProcAddr" get-instance-proc-addr) pfn-void-function
  (instance instance) ;; :OPTIONAL "true"
  (p-name :string) ;; :LEN "null-terminated"
)

(defvkextfun ("vkGetMemoryFdKHX" get-memory-fd-khx) checked-result
  (device device)
  (memory device-memory)
  (handle-type external-memory-handle-type-flag-bits-khx)
  (p-fd (:pointer :int)))

(defvkextfun ("vkGetMemoryFdPropertiesKHX" get-memory-fd-properties-khx) checked-result
  (device device)
  (handle-type external-memory-handle-type-flag-bits-khx)
  (fd :int)
  (p-memory-fd-properties (:pointer (:struct memory-fd-properties-khx))))

(defvkextfun ("vkGetMemoryWin32HandleKHX" get-memory-win32-handle-khx) checked-result
  (device device)
  (memory device-memory)
  (handle-type external-memory-handle-type-flag-bits-khx)
  (p-handle (:pointer handle)))

(defvkextfun ("vkGetMemoryWin32HandleNV" get-memory-win32-handle-nv) checked-result
  (device device)
  (memory device-memory)
  (handle-type external-memory-handle-type-flags-nv)
  (p-handle (:pointer handle)))

(defvkextfun ("vkGetMemoryWin32HandlePropertiesKHX" get-memory-win32-handle-properties-khx) checked-result
  (device device)
  (handle-type external-memory-handle-type-flag-bits-khx)
  (handle handle)
  (p-memory-win32-handle-properties (:pointer (:struct memory-win32-handle-properties-khx))))

(defvkextfun ("vkGetPastPresentationTimingGOOGLE" get-past-presentation-timing-google) checked-result
  (device device)
  (swapchain swapchain-khr) ;; :EXTERNSYNC "true"
  (p-presentation-timing-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-presentation-timings (:pointer (:struct past-presentation-timing-google))) ;; :OPTIONAL "true" :LEN "pPresentationTimingCount"
)

(defvkextfun ("vkGetPhysicalDeviceDisplayPlanePropertiesKHR" get-physical-device-display-plane-properties-khr) checked-result
  (physical-device physical-device)
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct display-plane-properties-khr))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkextfun ("vkGetPhysicalDeviceDisplayPropertiesKHR" get-physical-device-display-properties-khr) checked-result
  (physical-device physical-device)
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct display-properties-khr))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkextfun ("vkGetPhysicalDeviceExternalBufferPropertiesKHX" get-physical-device-external-buffer-properties-khx) :void
  (physical-device physical-device)
  (p-external-buffer-info (:pointer (:struct physical-device-external-buffer-info-khx)))
  (p-external-buffer-properties (:pointer (:struct external-buffer-properties-khx))))

(defvkextfun ("vkGetPhysicalDeviceExternalImageFormatPropertiesNV" get-physical-device-external-image-format-properties-nv) checked-result
  (physical-device physical-device)
  (format format)
  (type image-type)
  (tiling image-tiling)
  (usage image-usage-flags)
  (flags image-create-flags) ;; :OPTIONAL "true"
  (external-handle-type external-memory-handle-type-flags-nv) ;; :OPTIONAL "true"
  (p-external-image-format-properties (:pointer (:struct external-image-format-properties-nv))))

(defvkextfun ("vkGetPhysicalDeviceExternalSemaphorePropertiesKHX" get-physical-device-external-semaphore-properties-khx) :void
  (physical-device physical-device)
  (p-external-semaphore-info (:pointer (:struct physical-device-external-semaphore-info-khx)))
  (p-external-semaphore-properties (:pointer (:struct external-semaphore-properties-khx))))

(defvkfun ("vkGetPhysicalDeviceFeatures" get-physical-device-features) :void
  (physical-device physical-device)
  (p-features (:pointer (:struct physical-device-features))))

(defvkextfun ("vkGetPhysicalDeviceFeatures2KHR" get-physical-device-features-2-khr) :void
  (physical-device physical-device)
  (p-features (:pointer (:struct physical-device-features-2-khr))))

(defvkfun ("vkGetPhysicalDeviceFormatProperties" get-physical-device-format-properties) :void
  (physical-device physical-device)
  (format format)
  (p-format-properties (:pointer (:struct format-properties))))

(defvkextfun ("vkGetPhysicalDeviceFormatProperties2KHR" get-physical-device-format-properties-2-khr) :void
  (physical-device physical-device)
  (format format)
  (p-format-properties (:pointer (:struct format-properties-2-khr))))

(defvkextfun ("vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX" get-physical-device-generated-commands-properties-nvx) :void
  (physical-device physical-device)
  (p-features (:pointer (:struct device-generated-commands-features-nvx)))
  (p-limits (:pointer (:struct device-generated-commands-limits-nvx))))

(defvkfun ("vkGetPhysicalDeviceImageFormatProperties" get-physical-device-image-format-properties) checked-result
  (physical-device physical-device)
  (format format)
  (type image-type)
  (tiling image-tiling)
  (usage image-usage-flags)
  (flags image-create-flags) ;; :OPTIONAL "true"
  (p-image-format-properties (:pointer (:struct image-format-properties))))

(defvkextfun ("vkGetPhysicalDeviceImageFormatProperties2KHR" get-physical-device-image-format-properties-2-khr) checked-result
  (physical-device physical-device)
  (p-image-format-info (:pointer (:struct physical-device-image-format-info-2-khr)))
  (p-image-format-properties (:pointer (:struct image-format-properties-2-khr))))

(defvkfun ("vkGetPhysicalDeviceMemoryProperties" get-physical-device-memory-properties) :void
  (physical-device physical-device)
  (p-memory-properties (:pointer (:struct physical-device-memory-properties))))

(defvkextfun ("vkGetPhysicalDeviceMemoryProperties2KHR" get-physical-device-memory-properties-2-khr) :void
  (physical-device physical-device)
  (p-memory-properties (:pointer (:struct physical-device-memory-properties-2-khr))))

(defvkextfun ("vkGetPhysicalDeviceMirPresentationSupportKHR" get-physical-device-mir-presentation-support-khr) bool32
  (physical-device physical-device)
  (queue-family-index :uint32)
  (connection (:pointer mir-connection)))

(defvkextfun ("vkGetPhysicalDevicePresentRectanglesKHX" get-physical-device-present-rectangles-khx) checked-result
  (physical-device physical-device)
  (surface surface-khr) ;; :EXTERNSYNC "true"
  (p-rect-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-rects (:pointer (:struct rect-2d))) ;; :OPTIONAL "true" :LEN "pRectCount"
)

(defvkfun ("vkGetPhysicalDeviceProperties" get-physical-device-properties) :void
  (physical-device physical-device)
  (p-properties (:pointer (:struct physical-device-properties))))

(defvkextfun ("vkGetPhysicalDeviceProperties2KHR" get-physical-device-properties-2-khr) :void
  (physical-device physical-device)
  (p-properties (:pointer (:struct physical-device-properties-2-khr))))

(defvkfun ("vkGetPhysicalDeviceQueueFamilyProperties" get-physical-device-queue-family-properties) :void
  (physical-device physical-device)
  (p-queue-family-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-queue-family-properties (:pointer (:struct queue-family-properties))) ;; :OPTIONAL "true" :LEN "pQueueFamilyPropertyCount"
)

(defvkextfun ("vkGetPhysicalDeviceQueueFamilyProperties2KHR" get-physical-device-queue-family-properties-2-khr) :void
  (physical-device physical-device)
  (p-queue-family-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-queue-family-properties (:pointer (:struct queue-family-properties-2-khr))) ;; :OPTIONAL "true" :LEN "pQueueFamilyPropertyCount"
)

(defvkfun ("vkGetPhysicalDeviceSparseImageFormatProperties" get-physical-device-sparse-image-format-properties) :void
  (physical-device physical-device)
  (format format)
  (type image-type)
  (samples sample-count-flag-bits)
  (usage image-usage-flags)
  (tiling image-tiling)
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct sparse-image-format-properties))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkextfun ("vkGetPhysicalDeviceSparseImageFormatProperties2KHR" get-physical-device-sparse-image-format-properties-2-khr) :void
  (physical-device physical-device)
  (p-format-info (:pointer (:struct physical-device-sparse-image-format-info-2-khr)))
  (p-property-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-properties (:pointer (:struct sparse-image-format-properties-2-khr))) ;; :OPTIONAL "true" :LEN "pPropertyCount"
)

(defvkextfun ("vkGetPhysicalDeviceSurfaceCapabilities2EXT" get-physical-device-surface-capabilities-2-ext) checked-result
  (physical-device physical-device)
  (surface surface-khr)
  (p-surface-capabilities (:pointer (:struct surface-capabilities-2-ext))))

(defvkextfun ("vkGetPhysicalDeviceSurfaceCapabilities2KHR" get-physical-device-surface-capabilities-2-khr) checked-result
  (physical-device physical-device)
  (p-surface-info (:pointer (:struct physical-device-surface-info-2-khr)))
  (p-surface-capabilities (:pointer (:struct surface-capabilities-2-khr))))

(defvkextfun ("vkGetPhysicalDeviceSurfaceCapabilitiesKHR" get-physical-device-surface-capabilities-khr) checked-result
  (physical-device physical-device)
  (surface surface-khr)
  (p-surface-capabilities (:pointer (:struct surface-capabilities-khr))))

(defvkextfun ("vkGetPhysicalDeviceSurfaceFormats2KHR" get-physical-device-surface-formats-2-khr) checked-result
  (physical-device physical-device)
  (p-surface-info (:pointer (:struct physical-device-surface-info-2-khr)))
  (p-surface-format-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-surface-formats (:pointer (:struct surface-format-2-khr))) ;; :OPTIONAL "true" :LEN "pSurfaceFormatCount"
)

(defvkextfun ("vkGetPhysicalDeviceSurfaceFormatsKHR" get-physical-device-surface-formats-khr) checked-result
  (physical-device physical-device)
  (surface surface-khr)
  (p-surface-format-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-surface-formats (:pointer (:struct surface-format-khr))) ;; :OPTIONAL "true" :LEN "pSurfaceFormatCount"
)

(defvkextfun ("vkGetPhysicalDeviceSurfacePresentModesKHR" get-physical-device-surface-present-modes-khr) checked-result
  (physical-device physical-device)
  (surface surface-khr)
  (p-present-mode-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-present-modes (:pointer present-mode-khr)) ;; :OPTIONAL "true" :LEN "pPresentModeCount"
)

(defvkextfun ("vkGetPhysicalDeviceSurfaceSupportKHR" get-physical-device-surface-support-khr) checked-result
  (physical-device physical-device)
  (queue-family-index :uint32)
  (surface surface-khr)
  (p-supported (:pointer bool32)))

(defvkextfun ("vkGetPhysicalDeviceWaylandPresentationSupportKHR" get-physical-device-wayland-presentation-support-khr) bool32
  (physical-device physical-device)
  (queue-family-index :uint32)
  (display (:pointer (:struct wl_display))))

(defvkextfun ("vkGetPhysicalDeviceWin32PresentationSupportKHR" get-physical-device-win32-presentation-support-khr) bool32
  (physical-device physical-device)
  (queue-family-index :uint32))

(defvkextfun ("vkGetPhysicalDeviceXcbPresentationSupportKHR" get-physical-device-xcb-presentation-support-khr) bool32
  (physical-device physical-device)
  (queue-family-index :uint32)
  (connection (:pointer xcb_connection_t))
  (visual_id xcb_visualid_t))

(defvkextfun ("vkGetPhysicalDeviceXlibPresentationSupportKHR" get-physical-device-xlib-presentation-support-khr) bool32
  (physical-device physical-device)
  (queue-family-index :uint32)
  (dpy (:pointer display))
  (visual-id visual-id))

(defvkfun ("vkGetPipelineCacheData" get-pipeline-cache-data) checked-result
  (device device)
  (pipeline-cache pipeline-cache)
  (p-data-size (:pointer size-t)) ;; :OPTIONAL "false,true"
  (p-data (:pointer :void)) ;; :OPTIONAL "true" :LEN "pDataSize"
)

(defvkfun ("vkGetQueryPoolResults" get-query-pool-results) checked-result
  (device device)
  (query-pool query-pool)
  (first-query :uint32)
  (query-count :uint32)
  (data-size size-t)
  (p-data (:pointer :void)) ;; :LEN "dataSize"
  (stride device-size)
  (flags query-result-flags) ;; :OPTIONAL "true"
)

(defvkextfun ("vkGetRandROutputDisplayEXT" get-rand-r-output-display-ext) checked-result
  (physical-device physical-device)
  (dpy (:pointer display))
  (rr-output rr-output)
  (p-display (:pointer display-khr)))

(defvkextfun ("vkGetRefreshCycleDurationGOOGLE" get-refresh-cycle-duration-google) checked-result
  (device device)
  (swapchain swapchain-khr) ;; :EXTERNSYNC "true"
  (p-display-timing-properties (:pointer (:struct refresh-cycle-duration-google))))

(defvkfun ("vkGetRenderAreaGranularity" get-render-area-granularity) :void
  (device device)
  (render-pass render-pass)
  (p-granularity (:pointer (:struct extent-2d))))

(defvkextfun ("vkGetSemaphoreFdKHX" get-semaphore-fd-khx) checked-result
  (device device)
  (semaphore semaphore)
  (handle-type external-semaphore-handle-type-flag-bits-khx)
  (p-fd (:pointer :int)))

(defvkextfun ("vkGetSemaphoreWin32HandleKHX" get-semaphore-win32-handle-khx) checked-result
  (device device)
  (semaphore semaphore)
  (handle-type external-semaphore-handle-type-flag-bits-khx)
  (p-handle (:pointer handle)))

(defvkextfun ("vkGetSwapchainCounterEXT" get-swapchain-counter-ext) checked-result
  (device device)
  (swapchain swapchain-khr)
  (counter surface-counter-flag-bits-ext)
  (p-counter-value (:pointer :uint64)))

(defvkextfun ("vkGetSwapchainImagesKHR" get-swapchain-images-khr) checked-result
  (device device)
  (swapchain swapchain-khr)
  (p-swapchain-image-count (:pointer :uint32)) ;; :OPTIONAL "false,true"
  (p-swapchain-images (:pointer image)) ;; :OPTIONAL "true" :LEN "pSwapchainImageCount"
)

(defvkextfun ("vkGetSwapchainStatusKHR" get-swapchain-status-khr) checked-result
  (device device)
  (swapchain swapchain-khr) ;; :EXTERNSYNC "true"
)

(defvkextfun ("vkImportSemaphoreFdKHX" import-semaphore-fd-khx) checked-result
  (device device)
  (p-import-semaphore-fd-info (:pointer (:struct import-semaphore-fd-info-khx))))

(defvkextfun ("vkImportSemaphoreWin32HandleKHX" import-semaphore-win32-handle-khx) checked-result
  (device device)
  (p-import-semaphore-win32-handle-info (:pointer (:struct import-semaphore-win32-handle-info-khx))))

(defvkfun ("vkInvalidateMappedMemoryRanges" invalidate-mapped-memory-ranges) checked-result
  (device device)
  (memory-range-count :uint32)
  (p-memory-ranges (:pointer (:struct mapped-memory-range))) ;; :LEN "memoryRangeCount"
)

(defvkfun ("vkMapMemory" map-memory) checked-result
  (device device)
  (memory device-memory) ;; :EXTERNSYNC "true"
  (offset device-size)
  (size device-size)
  (flags memory-map-flags) ;; :OPTIONAL "true"
  (pp-data (:pointer (:pointer :void))))

(defvkfun ("vkMergePipelineCaches" merge-pipeline-caches) checked-result
  (device device)
  (dst-cache pipeline-cache) ;; :EXTERNSYNC "true"
  (src-cache-count :uint32)
  (p-src-caches (:pointer pipeline-cache)) ;; :LEN "srcCacheCount"
)

(defvkfun ("vkQueueBindSparse" queue-bind-sparse) checked-result
  (queue queue) ;; :EXTERNSYNC "true"
  (bind-info-count :uint32) ;; :OPTIONAL "true"
  (p-bind-info (:pointer (:struct bind-sparse-info))) ;; :LEN "bindInfoCount" :EXTERNSYNC "pBindInfo[].pWaitSemaphores[],pBindInfo[].pSignalSemaphores[],pBindInfo[].pBufferBinds[].buffer,pBindInfo[].pImageOpaqueBinds[].image,pBindInfo[].pImageBinds[].image"
  (fence fence) ;; :OPTIONAL "true" :EXTERNSYNC "true"
)

(defvkextfun ("vkQueuePresentKHR" queue-present-khr) checked-result
  (queue queue) ;; :EXTERNSYNC "true"
  (p-present-info (:pointer (:struct present-info-khr))) ;; :EXTERNSYNC "pPresentInfo.pWaitSemaphores[],pPresentInfo.pSwapchains[]"
)

(defvkfun ("vkQueueSubmit" queue-submit) checked-result
  (queue queue) ;; :EXTERNSYNC "true"
  (submit-count :uint32) ;; :OPTIONAL "true"
  (p-submits (:pointer (:struct submit-info))) ;; :LEN "submitCount" :EXTERNSYNC "pSubmits[].pWaitSemaphores[],pSubmits[].pSignalSemaphores[]"
  (fence fence) ;; :OPTIONAL "true" :EXTERNSYNC "true"
)

(defvkfun ("vkQueueWaitIdle" queue-wait-idle) checked-result
  (queue queue))

(defvkextfun ("vkRegisterDeviceEventEXT" register-device-event-ext) checked-result
  (device device)
  (p-device-event-info (:pointer (:struct device-event-info-ext)))
  (p-allocator (:pointer (:struct allocation-callbacks)))
  (p-fence (:pointer fence)))

(defvkextfun ("vkRegisterDisplayEventEXT" register-display-event-ext) checked-result
  (device device)
  (display display-khr)
  (p-display-event-info (:pointer (:struct display-event-info-ext)))
  (p-allocator (:pointer (:struct allocation-callbacks)))
  (p-fence (:pointer fence)))

(defvkextfun ("vkRegisterObjectsNVX" register-objects-nvx) checked-result
  (device device)
  (object-table object-table-nvx) ;; :EXTERNSYNC "true"
  (object-count :uint32)
  (pp-object-table-entries (:pointer (:pointer (:struct object-table-entry-nvx)))) ;; :LEN "objectCount"
  (p-object-indices (:pointer :uint32)) ;; :LEN "objectCount"
)

(defvkextfun ("vkReleaseDisplayEXT" release-display-ext) checked-result
  (physical-device physical-device)
  (display display-khr))

(defvkfun ("vkResetCommandBuffer" reset-command-buffer) checked-result
  (command-buffer command-buffer) ;; :EXTERNSYNC "true"
  (flags command-buffer-reset-flags) ;; :OPTIONAL "true"
)

(defvkfun ("vkResetCommandPool" reset-command-pool) checked-result
  (device device)
  (command-pool command-pool) ;; :EXTERNSYNC "true"
  (flags command-pool-reset-flags) ;; :OPTIONAL "true"
)

(defvkfun ("vkResetDescriptorPool" reset-descriptor-pool) checked-result
  (device device)
  (descriptor-pool descriptor-pool) ;; :EXTERNSYNC "true"
  (flags descriptor-pool-reset-flags) ;; :OPTIONAL "true"
)

(defvkfun ("vkResetEvent" reset-event) checked-result
  (device device)
  (event event) ;; :EXTERNSYNC "true"
)

(defvkfun ("vkResetFences" reset-fences) checked-result
  (device device)
  (fence-count :uint32)
  (p-fences (:pointer fence)) ;; :LEN "fenceCount" :EXTERNSYNC "true"
)

(defvkfun ("vkSetEvent" set-event) checked-result
  (device device)
  (event event) ;; :EXTERNSYNC "true"
)

(defvkextfun ("vkSetHdrMetadataEXT" set-hdr-metadata-ext) :void
  (device device)
  (swapchain-count :uint32)
  (p-swapchains (:pointer swapchain-khr)) ;; :LEN "swapchainCount"
  (p-metadata (:pointer (:struct hdr-metadata-ext))) ;; :LEN "swapchainCount"
)

(defvkextfun ("vkTrimCommandPoolKHR" trim-command-pool-khr) :void
  (device device)
  (command-pool command-pool) ;; :EXTERNSYNC "true"
  (flags command-pool-trim-flags-khr) ;; :OPTIONAL "true"
)

(defvkfun ("vkUnmapMemory" unmap-memory) :void
  (device device)
  (memory device-memory) ;; :EXTERNSYNC "true"
)

(defvkextfun ("vkUnregisterObjectsNVX" unregister-objects-nvx) checked-result
  (device device)
  (object-table object-table-nvx) ;; :EXTERNSYNC "true"
  (object-count :uint32)
  (p-object-entry-types (:pointer object-entry-type-nvx)) ;; :LEN "objectCount"
  (p-object-indices (:pointer :uint32)) ;; :LEN "objectCount"
)

(defvkextfun ("vkUpdateDescriptorSetWithTemplateKHR" update-descriptor-set-with-template-khr) :void
  (device device)
  (descriptor-set descriptor-set) ;; :EXTERNSYNC "true"
  (descriptor-update-template descriptor-update-template-khr)
  (p-data (:pointer :void)))

(defvkfun ("vkUpdateDescriptorSets" update-descriptor-sets) :void
  (device device)
  (descriptor-write-count :uint32) ;; :OPTIONAL "true"
  (p-descriptor-writes (:pointer (:struct write-descriptor-set))) ;; :LEN "descriptorWriteCount" :EXTERNSYNC "pDescriptorWrites[].dstSet"
  (descriptor-copy-count :uint32) ;; :OPTIONAL "true"
  (p-descriptor-copies (:pointer (:struct copy-descriptor-set))) ;; :LEN "descriptorCopyCount" :EXTERNSYNC "pDescriptorCopies[].dstSet"
)

(defvkfun ("vkWaitForFences" wait-for-fences) checked-result
  (device device)
  (fence-count :uint32)
  (p-fences (:pointer fence)) ;; :LEN "fenceCount"
  (wait-all bool32)
  (timeout :uint64))

