(defpackage #:cl-vulkan
  (:use :cl :cffi)
  (:nicknames :vk)
  (:import-from
   #:%vk
   #:not-ready
   #:timeout
   #:event-set
   #:event-reset
   #:incomplete
   #:suboptimal-khr
   #:error-out-of-host-memory
   #:error-out-of-device-memory
   #:error-initialization-failed
   #:error-device-lost
   #:error-memory-map-failed
   #:error-layer-not-present
   #:error-extension-not-present
   #:error-feature-not-present
   #:error-incompatible-driver
   #:error-too-many-objects
   #:error-format-not-supported
   #:error-surface-lost-khr
   #:error-native-window-in-use-khr
   #:error-out-of-date-khr
   #:error-incompatible-display-khr
   #:error-validation-failed-ext
   #:nv-extension-0-error
   #:nv-extension-1-error

   #:device-wait-idle
   #:get-device-proc-addr
   #:get-event-status
   #:get-fence-status
   #:get-instance-proc-addr
   #:get-physical-device-mir-presentation-support-khr
   #:get-physical-device-wayland-presentation-support-khr
   #:get-physical-device-win32-presentation-support-khr
   #:get-physical-device-xlib-presentation-support-khr
   #:get-physical-device-xcb-presentation-support-khr
   #:queue-wait-idle)
  (:export
   #:not-ready
   #:timeout
   #:event-set
   #:event-reset
   #:incomplete
   #:suboptimal-khr

   #:error-out-of-host-memory
   #:error-out-of-device-memory
   #:error-initialization-failed
   #:error-device-lost
   #:error-memory-map-failed
   #:error-layer-not-present
   #:error-extension-not-present
   #:error-feature-not-present
   #:error-incompatible-driver
   #:error-too-many-objects
   #:error-format-not-supported
   #:error-surface-lost-khr
   #:error-native-window-in-use-khr
   #:error-out-of-date-khr
   #:error-incompatible-display-khr
   #:error-validation-failed-ext
   #:nv-extension-0-error
   #:nv-extension-1-error

   #:with-instance
   #:enumerate-physical-devices
   #:get-physical-device-properties
   #:get-physical-device-queue-family-properties
   #:get-physical-device-memory-properties
   #:with-device
   #:get-physical-device-features
   #:decode-version
   #:enumerate-instance-layer-properties
   #:enumerate-instance-extension-properties
   #:with-debug-report
   #:get-physical-device-surface-support-khr
   #:get-physical-device-mir-presentation-support-khr
   #:get-physical-device-wayland-presentation-support-khr
   #:get-physical-device-win32-presentation-support-khr
   #:get-physical-device-xlib-presentation-support-khr
   #:get-physical-device-xcb-presentation-support-khr
   #:with-win32-surface-khr
   #:get-physical-device-surface-formats-khr
   #:with-swapchain
   #:get-physical-device-surface-present-modes-khr
   #:create-command-pool
   #:create-swapchain-khr
   #:destroy-swapchain-khr
   #:get-swapchain-images-khr
   #:acquire-next-image-khr
   #:allocate-command-buffers
   #:device-wait-idle
   #:destroy-command-pool
   #:destroy-image-view
   #:with-command-buffers
   #:with-commands
   #:create-image-view
   #:queue-submit1
   #:queue-wait-idle
   #:cmd-pipeline-barrier))
