# This is a basic workflow to help you get started with Actions

name: test-vulkan-versions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'vk-generator.asd'
      - 'src/**'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  test-vulkan-versions:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vulkan-sdk:
          - "1.2.198"
          - "1.2.189"
          - "1.2.182"
          - "1.2.176"
          - "1.2.170"
          - "1.2.162"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup environment
        run: |
          # Add lunarg apt sources
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          if [ "${{ matrix.vulkan-sdk }}" = "latest" ]; then
            sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
          else
            sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{ matrix.vulkan-sdk }}-focal.list https://packages.lunarg.com/vulkan/${{ matrix.vulkan-sdk }}/lunarg-vulkan-${{ matrix.vulkan-sdk }}-focal.list
          fi
          
          # Update package lists
          sudo apt-get update -qq
          
          # Install dependencies
          sudo apt-get install -y \
            vulkan-sdk
          
          ### Install SBCL & Quicklisp
          sudo apt-get install sbcl
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          curl -O https://beta.quicklisp.org/quicklisp.lisp.asc
          sbcl \
            --non-interactive \
            --load quicklisp.lisp \
            --eval '(quicklisp-quickstart:install)' \
            --eval '
              (let ((ql-util::*do-not-prompt* t))
                (ql:add-to-init-file)
                (sb-ext:quit))
            '

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy project to quicklisp local-projects
        run: |
          cp -r ../${{ github.event.repository.name }} ~/quicklisp/local-projects

      - name: Generate bindings
        run: |
          sbcl \
            --non-interactive \
            --eval "(ql:quickload :vk-generator)" \
            --eval "(vk-generator:generate :version \"v${{ matrix.vulkan-sdk }}\")" \
            --eval "(ql:quickload :vk)" \
            --eval "(sb-ext:quit)"
